CREATE TABLE `heroku_4b09a6c99bdb348`.`usuario` (
  `BDCODIGO` INT NOT NULL COMMENT '',
  `BDLOGIN` VARCHAR(100) NOT NULL COMMENT '',
  `BDSALT` INT NOT NULL COMMENT '',
  `BDHASH` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`BDCODIGO`)  COMMENT '');

 CREATE TABLE `heroku_4b09a6c99bdb348`.`perfil` (
  `BDCODIGO` INT NOT NULL COMMENT '',
  `BDNOME` VARCHAR(80) NOT NULL COMMENT '',
  `BDDATANASC` DATETIME NOT NULL COMMENT '',
  `BDCELULAR` VARCHAR(11) NOT NULL COMMENT '',
  `BDEMAIL` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`BDCODIGO`)  COMMENT '',
  CONSTRAINT `FK_USUARIO_PERFIL`
    FOREIGN KEY (`BDCODIGO`)
    REFERENCES `heroku_4b09a6c99bdb348`.`usuario` (`BDCODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE `heroku_4b09a6c99bdb348`.`animal` (
  `BDCODUSU` INT NOT NULL COMMENT '',
  `BDCODANIMAL` INT NOT NULL COMMENT '',
  `BDNOME` VARCHAR(50) NOT NULL COMMENT '',
  `BDCOR` VARCHAR(50) NOT NULL COMMENT '',
  `BDSEXO` VARCHAR(1) NOT NULL COMMENT '',
  `BDRACA` VARCHAR(45) NOT NULL COMMENT '',
  `BDDESC` VARCHAR(100) NULL COMMENT '',
  `BDFOTO` BLOB NULL COMMENT '',
  `BDESPECIE` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`BDCODUSU`, `BDCODANIMAL`)  COMMENT '',
  CONSTRAINT `FK_ANIMAL_USU`
    FOREIGN KEY (`BDCODUSU`)
    REFERENCES `heroku_4b09a6c99bdb348`.`usuario` (`BDCODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

	
CREATE TABLE `heroku_4b09a6c99bdb348`.`anuncio` (
  `BDCODUSU` INT NOT NULL COMMENT '',
  `BDCODANIMAL` INT NOT NULL COMMENT '',
  `BDCODANUNCIO` INT NOT NULL COMMENT '',
  `BDTIPO` INT NOT NULL COMMENT '',
  `BDDATAHORA` DATETIME NOT NULL COMMENT '',
  `BDLONG` DECIMAL NOT NULL COMMENT '',
  `BDLAT` DECIMAL NOT NULL COMMENT '',
  `BDDURACAO` INT NOT NULL COMMENT '',
  `BDDESCRICAO` VARCHAR(300) NULL COMMENT '',
  `BDFOTO` BLOB NULL COMMENT '',
  PRIMARY KEY (`BDCODUSU`, `BDCODANIMAL`, `BDCODANUNCIO`)  COMMENT '',
  CONSTRAINT `FK_ANUN_ANI`
    FOREIGN KEY (`BDCODUSU` , `BDCODANIMAL`)
    REFERENCES `heroku_4b09a6c99bdb348`.`animal` (`BDCODUSU` , `BDCODANIMAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `heroku_4b09a6c99bdb348`.`usuario` (`BDCODIGO`, `BDLOGIN`, `BDSALT`, `BDHASH`) VALUES ('1', 'maiconwazo', '1010', '1010101010101');
INSERT INTO `heroku_4b09a6c99bdb348`.`usuario` (`BDCODIGO`, `BDLOGIN`, `BDSALT`, `BDHASH`) VALUES ('2', 'guigostosao', '2020', '2020202220202');
INSERT INTO `heroku_4b09a6c99bdb348`.`usuario` (`BDCODIGO`, `BDLOGIN`, `BDSALT`, `BDHASH`) VALUES ('3', 'petypety', '3030', '3030303030303');

INSERT INTO `heroku_4b09a6c99bdb348`.`animal` (`BDCODUSU`, `BDCODANIMAL`, `BDNOME`, `BDCOR`, `BDSEXO`, `BDRACA`, `BDDESC`, `BDESPECIE`) VALUES ('3', '1', 'STARK', 'MARROM', 'M', 'SRD', 'PREGUIÇOSO E NÃO CARINHOSO', 'CACHORRO');
INSERT INTO `heroku_4b09a6c99bdb348`.`animal` (`BDCODUSU`, `BDCODANIMAL`, `BDNOME`, `BDCOR`, `BDSEXO`, `BDRACA`, `BDDESC`, `BDESPECIE`) VALUES ('3', '2', 'BRUCE', 'MARROM', 'M', 'SRD', 'HIPERATIVO E CARINHOSO', 'CACHORRO');
INSERT INTO `heroku_4b09a6c99bdb348`.`animal` (`BDCODUSU`, `BDCODANIMAL`, `BDNOME`, `BDCOR`, `BDSEXO`, `BDRACA`, `BDDESC`, `BDESPECIE`) VALUES ('1', '1', 'CINDI', 'BRANCO', 'F', 'SRD', 'EXTRAMENTE CARINHOSA', 'GATO');
INSERT INTO `heroku_4b09a6c99bdb348`.`animal` (`BDCODUSU`, `BDCODANIMAL`, `BDNOME`, `BDCOR`, `BDSEXO`, `BDRACA`, `BDDESC`, `BDESPECIE`) VALUES ('2', '1', 'SPIKE', 'BEGE', 'M', 'SRD', 'HIPERATIVO E MEDROSO', 'CACHORRO');

INSERT INTO `heroku_4b09a6c99bdb348`.`perfil` (`BDCODIGO`, `BDNOME`, `BDDATANASC`, `BDCELULAR`, `BDEMAIL`) VALUES ('3', 'PETERSON', '09/04/1981', '47991889184', 'petersonbonib@gmail.com');
INSERT INTO `heroku_4b09a6c99bdb348`.`perfil` (`BDCODIGO`, `BDNOME`, `BDDATANASC`, `BDCELULAR`, `BDEMAIL`) VALUES ('2', 'GUILHERME', '27/10/1996', '47992846505', 'guilherme.drbacca@gmail.com');
INSERT INTO `heroku_4b09a6c99bdb348`.`perfil` (`BDCODIGO`, `BDNOME`, `BDDATANASC`, `BDCELULAR`, `BDEMAIL`) VALUES ('1', 'MAICON', '18/05/1996', '47992929352', 'maiconsantos2501@gmail.com');

INSERT INTO `heroku_4b09a6c99bdb348`.`anuncio` (`BDCODUSU`, `BDCODANIMAL`, `BDCODANUNCIO`, `BDTIPO`, `BDDATAHORA`, `BDLONG`, `BDLAT`, `BDDURACAO`, `BDDESCRICAO`) VALUES ('1', '1', '1', '1', '10/05/2018', '200', '300', '10', 'PERTO DO MERCADO');
INSERT INTO `heroku_4b09a6c99bdb348`.`anuncio` (`BDCODUSU`, `BDCODANIMAL`, `BDCODANUNCIO`, `BDTIPO`, `BDDATAHORA`, `BDLONG`, `BDLAT`, `BDDURACAO`, `BDDESCRICAO`) VALUES ('2', '1', '1', '1', '08/05/2018', '300', '300', '5', 'PERTO DA PADARIA');
INSERT INTO `heroku_4b09a6c99bdb348`.`anuncio` (`BDCODUSU`, `BDCODANIMAL`, `BDCODANUNCIO`, `BDTIPO`, `BDDATAHORA`, `BDLONG`, `BDLAT`, `BDDURACAO`, `BDDESCRICAO`) VALUES ('3', '2', '1', '1', '01/05/2018', '200', '100', '2', 'PERTO DA FURB');
